from __future__ import annotations

from pathlib import Path
import unittest

ROOT = Path(__file__).resolve().parents[1]
MIGRATION = ROOT / "docs" / "MIGRATION_RUNBOOK.md"
KNOWLEDGE = ROOT / "docs" / "PROJECT_KNOWLEDGE.md"
SUPPLY_CHAIN = ROOT / "docs" / "SUPPLY_CHAIN.md"
PUBLIC_READINESS = ROOT / "docs" / "PUBLIC_READINESS.md"


def compact_markdown(text: str) -> str:
    return " ".join(text.split())


class CurrentOperationalDocsTests(unittest.TestCase):
    def test_migration_runbook_is_archival_not_retired_runner_instructions(self) -> None:
        text = MIGRATION.read_text(encoding="utf-8")
        compact = compact_markdown(text)
        for required in (
            "# Migration runbook — archived",
            "completed historical record",
            "Do not reconstruct or execute",
            "rozkalns-cv-pull-deploy.timer",
            "AUTO_DEPLOY_SAFE",
        ):
            self.assertIn(required, compact)

        for stale_instruction in (
            "bash runner/activate-github-main-deploy.sh",
            "Deploy merged main to RPi5",
            "github-cv-runner",
            "rozkalns-cv-release",
            "bash scripts/bootstrap-github.sh",
            "cloudflared.env",
        ):
            self.assertNotIn(stale_instruction, text)

    def test_project_knowledge_tracks_current_pull_and_ingress_boundaries(self) -> None:
        text = KNOWLEDGE.read_text(encoding="utf-8")
        compact = compact_markdown(text)
        for required in (
            "Application services: `cv` (nginx) and `cvbot` (Python assistant)",
            "http://127.0.0.1:8088/",
            "Direct LAN publish: none",
            "systemd `cloudflared.service`",
            "public `rozkalnsandris/rozkalns-cv`",
            "GitHub Actions provides CI/security evidence only",
            "rozkalns-cv-pull-deploy.timer",
            "AUTO_DEPLOY_SAFE",
            "deploys only `cv` and `cvbot`",
        ):
            self.assertIn(required, compact)

        for stale_current_claim in (
            "Tunnel service/container: `cv-cloudflared`",
            "Private repository: `rozkalnsandris/rozkalns-cv`",
            "Every successful push CI on `main` queues a serial production deployment",
            "Dedicated runner label: `rozkalns-cv-release`",
            "Cloudflare ingress for the root domain points to `http://cv:80`",
        ):
            self.assertNotIn(stale_current_claim, text)

    def test_supply_chain_procedure_tracks_current_lock_ingress_and_pull_transport(self) -> None:
        text = SUPPLY_CHAIN.read_text(encoding="utf-8")
        compact = compact_markdown(text)
        for required in (
            "`bot/requirements.in` with the three reviewed direct dependencies",
            "`bot/requirements.txt` generated by `pip-compile --generate-hashes`",
            "hash-complete `bot/requirements.txt`",
            "host-wide infrastructure owned by `RPi5_main`",
            "systemd `cloudflared.service`",
            "pull-controller preflight independently resolves current `origin/main`",
            "installed root-owned deploy-library and pull wrapper blobs",
            "The preflight itself never authorizes production mutation",
        ):
            self.assertIn(required, compact)

        for stale_current_claim in (
            "bot/requirements.lock",
            "shared `cv-cloudflared` container",
            "The production tunnel image is declaratively pinned",
            "The deploy workflow additionally hashes the installed root-owned host helper",
        ):
            self.assertNotIn(stale_current_claim, text)

    def test_public_readiness_final_baseline_is_explicitly_historical(self) -> None:
        text = PUBLIC_READINESS.read_text(encoding="utf-8")
        compact = compact_markdown(text)
        for required in (
            "Historical evidence snapshot",
            "Do not use the `Final baseline` section to determine current `main`, production SHA, deploy status, or active work queue",
            "current operational architecture, use `docs/PROJECT_KNOWLEDGE.md`",
            "canonical issue #347 and its latest title/comments",
            "At the start of this final readiness declaration",
            "0d2c4f97708e509968358e56525fc0df864173d7",
            "edea046966b8e69c14fb652b799297b9ae1df1bf",
        ):
            self.assertIn(required, compact)


if __name__ == "__main__":
    unittest.main()
