#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
APP_PATH = ROOT / "bot" / "app.py"
PROMPT_PATH = ROOT / "bot" / "system_prompt.txt"
LOADER_PATH = ROOT / "bot" / "system_prompt.py"


class PromptSyncError(RuntimeError):
    pass


def validate_prompt_boundary(app_text: str, prompt: str, loader_text: str) -> None:
    if not prompt.strip():
        raise PromptSyncError("generated prompt resource is empty")
    for forbidden in (
        "# BEGIN GENERATED SYSTEM PROMPT",
        "# END GENERATED SYSTEM PROMPT",
        'SYSTEM_PROMPT = """',
    ):
        if forbidden in app_text:
            raise PromptSyncError("bot/app.py still embeds generated prompt content")
    if "from system_prompt import load_system_prompt" not in app_text:
        raise PromptSyncError("bot/app.py does not use the generated prompt resource loader")
    if 'with_name("system_prompt.txt")' not in loader_text:
        raise PromptSyncError("system prompt loader does not target system_prompt.txt")
    if "read_text(encoding=\"utf-8\")" not in loader_text:
        raise PromptSyncError("system prompt loader does not read UTF-8 resource content")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        app_text = APP_PATH.read_text(encoding="utf-8")
        prompt = PROMPT_PATH.read_text(encoding="utf-8")
        loader_text = LOADER_PATH.read_text(encoding="utf-8")
        validate_prompt_boundary(app_text, prompt, loader_text)
        if args.write:
            # The canonical prompt resource is generated by build-content.py.
            # There is intentionally no second copy to synchronize into app.py.
            pass
    except (OSError, PromptSyncError) as error:
        print(f"PROMPT_SYNC=FAIL ERROR={error}", file=sys.stderr)
        return 1
    print("PROMPT_SYNC=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
