name: Workflow security

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "renovate.json"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  workflow-security:
    name: GitHub Actions static analysis
    uses: rozkalnsandris/ops-workflows/.github/workflows/workflow-security.yml@0450e662093c41e98ca96802b523ac91eb02e5fe
    permissions:
      contents: read
